package com.tonic.j2cs.naming;

import com.tonic.j2cs.types.CsType;
import com.tonic.j2cs.types.TypeMapper;
import com.tonic.parser.ClassFile;
import com.tonic.parser.FieldEntry;
import com.tonic.parser.MethodEntry;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Assigns deterministic, collision-free C# member names for one class.
 * Fields claim names first; distinct Java method names never share a C# name; overloads of the
 * same Java name that differ only by return type get a __r return-descriptor suffix.
 * Names generated by the constructor protocol (__init_*) and the class name itself are reserved.
 */
public final class MemberNamer {

    private static final Map<String, String> OBJECT_OVERRIDES = Map.of(
            "toString()Ljava/lang/String;", "toString",
            "hashCode()I", "hashCode",
            "equals(Ljava/lang/Object;)Z", "equals");

    private final Map<String, String> methodNames = new LinkedHashMap<>();
    private final Map<String, String> fieldNames = new LinkedHashMap<>();

    public MemberNamer(ClassFile classFile, TypeMapper typeMapper) {
        Set<String> taken = new HashSet<>();
        taken.add(CsNamer.classNameOf(classFile.getClassName()));
        for (MethodEntry method : classFile.getMethods()) {
            if (method.getName().equals("<init>")) {
                taken.add(initMethodName(method.getDesc()));
            }
            String override = OBJECT_OVERRIDES.get(key(method.getName(), method.getDesc()));
            if (override != null) {
                methodNames.put(key(method.getName(), method.getDesc()), override);
                taken.add(override);
            }
        }
        assignFieldNames(classFile, taken);
        assignMethodNames(classFile, typeMapper, taken);
    }

    public static boolean isObjectOverride(String name, String descriptor) {
        return OBJECT_OVERRIDES.containsKey(key(name, descriptor));
    }

    public String methodName(MethodEntry method) {
        return methodName(method.getName(), method.getDesc());
    }

    public String methodName(String name, String descriptor) {
        String assigned = methodNames.get(key(name, descriptor));
        if (assigned == null) {
            throw new IllegalArgumentException("no name assigned for method " + name + descriptor);
        }
        return assigned;
    }

    public String fieldName(FieldEntry field) {
        String name = fieldNames.get(key(field.getName(), field.getDesc()));
        if (name == null) {
            throw new IllegalArgumentException("no name assigned for field " + field.getName() + " " + field.getDesc());
        }
        return name;
    }

    public static String initMethodName(String descriptor) {
        return "__init" + descriptorSuffix(descriptor);
    }

    public static String descriptorSuffix(String descriptor) {
        StringBuilder sb = new StringBuilder(descriptor.length());
        for (int i = 0; i < descriptor.length(); i++) {
            char c = descriptor.charAt(i);
            if (c == '/' || c == '(' || c == ')' || c == ';' || c == '[') {
                sb.append('_');
            } else if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
                sb.append(c);
            } else {
                sb.append("_u").append(String.format("%04X", (int) c)).append('_');
            }
        }
        return sb.toString();
    }

    private void assignFieldNames(ClassFile classFile, Set<String> taken) {
        for (FieldEntry field : classFile.getFields()) {
            String candidate = unique(CsNamer.identifier(field.getName()), taken);
            taken.add(candidate);
            fieldNames.put(key(field.getName(), field.getDesc()), candidate);
        }
    }

    private void assignMethodNames(ClassFile classFile, TypeMapper typeMapper, Set<String> taken) {
        Map<String, String> baseByJavaName = new LinkedHashMap<>();
        List<MethodEntry> ordinary = new ArrayList<>();
        for (MethodEntry method : classFile.getMethods()) {
            String name = method.getName();
            if (name.equals("<init>") || name.equals("<clinit>")
                    || methodNames.containsKey(key(name, method.getDesc()))) {
                continue;
            }
            ordinary.add(method);
            if (!baseByJavaName.containsKey(name)) {
                String candidate = unique(CsNamer.identifier(name), taken);
                taken.add(candidate);
                baseByJavaName.put(name, candidate);
            }
        }
        Map<String, List<MethodEntry>> byBaseAndParams = new LinkedHashMap<>();
        for (MethodEntry method : ordinary) {
            String group = baseByJavaName.get(method.getName()) + "|" + paramSignature(method.getDesc(), typeMapper);
            byBaseAndParams.computeIfAbsent(group, g -> new ArrayList<>()).add(method);
        }
        for (List<MethodEntry> group : byBaseAndParams.values()) {
            for (MethodEntry method : group) {
                String base = baseByJavaName.get(method.getName());
                String name = group.size() == 1
                        ? base
                        : base + "__r" + descriptorSuffix(returnDescriptor(method.getDesc()));
                methodNames.put(key(method.getName(), method.getDesc()), name);
            }
        }
    }

    private static String unique(String base, Set<String> taken) {
        String candidate = base;
        int n = 2;
        while (taken.contains(candidate)) {
            candidate = base + "__" + n++;
        }
        return candidate;
    }

    private static String paramSignature(String methodDescriptor, TypeMapper typeMapper) {
        StringBuilder sb = new StringBuilder();
        for (CsType param : typeMapper.paramTypes(methodDescriptor)) {
            sb.append(param.csText()).append(',');
        }
        return sb.toString();
    }

    private static String returnDescriptor(String methodDescriptor) {
        return methodDescriptor.substring(methodDescriptor.indexOf(')') + 1);
    }

    private static String key(String name, String descriptor) {
        return name + descriptor;
    }
}
