package com.tonic.j2cs.naming;

import com.tonic.j2cs.types.CsType;
import com.tonic.j2cs.types.TypeMapper;
import com.tonic.parser.ClassFile;
import com.tonic.parser.FieldEntry;
import com.tonic.parser.MethodEntry;
import com.tonic.util.Modifiers;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Assigns deterministic, collision-free C# member names for one class, coordinated with its
 * supertypes: a method whose (name, descriptor) is declared in an ancestor reuses the ancestor's
 * C# name verbatim so C# override linkage holds, and every inherited member name is reserved so
 * new members can never hide or hijack inherited ones. Fields claim names before methods;
 * return-type-only overloads get a __r suffix; names generated by the constructor protocol
 * (__init_*), the class name, and the Object trio are always reserved.
 */
public final class MemberNamer {

    private static final Map<String, String> OBJECT_OVERRIDES = Map.of(
            "toString()Ljava/lang/String;", "toString",
            "hashCode()I", "hashCode",
            "equals(Ljava/lang/Object;)Z", "equals");

    private final Map<String, String> methodNames = new LinkedHashMap<>();
    private final Map<String, Integer> methodAccess = new LinkedHashMap<>();
    private final Map<String, String> fieldNames = new LinkedHashMap<>();
    private final Map<String, String> inheritedAssignments;
    private final Set<String> taken = new HashSet<>();
    private final Set<String> localReserved = new HashSet<>();
    private boolean classNameConflict;

    public MemberNamer(ClassFile classFile, TypeMapper typeMapper) {
        this(classFile, typeMapper, Map.of(), Set.of());
    }

    public MemberNamer(ClassFile classFile, TypeMapper typeMapper,
                       Map<String, String> inheritedAssignments, Set<String> inheritedTaken) {
        this.inheritedAssignments = Map.copyOf(inheritedAssignments);
        String csClassName = CsNamer.classNameOf(classFile.getClassName());
        taken.add(csClassName);
        localReserved.add(csClassName);
        taken.addAll(OBJECT_OVERRIDES.values());
        localReserved.addAll(OBJECT_OVERRIDES.values());
        taken.addAll(inheritedTaken);
        for (MethodEntry method : classFile.getMethods()) {
            String key = key(method.getName(), method.getDesc());
            methodAccess.put(key, method.getAccess());
            if (method.getName().equals("<init>")) {
                taken.add(initMethodName(method.getDesc()));
                localReserved.add(initMethodName(method.getDesc()));
            }
            String override = OBJECT_OVERRIDES.get(key);
            if (override != null) {
                methodNames.put(key, override);
            }
        }
        adoptInheritedNames(classFile, csClassName);
        assignFieldNames(classFile, taken);
        assignMethodNames(classFile, typeMapper, taken);
    }

    private void adoptInheritedNames(ClassFile classFile, String csClassName) {
        for (MethodEntry method : classFile.getMethods()) {
            String name = method.getName();
            if (name.equals("<init>") || name.equals("<clinit>")) {
                continue;
            }
            String key = key(name, method.getDesc());
            if (methodNames.containsKey(key)) {
                continue;
            }
            String inherited = inheritedAssignments.get(key);
            if (inherited == null
                    || Modifiers.isPrivate(method.getAccess())
                    || Modifiers.isStatic(method.getAccess())) {
                continue;
            }
            methodNames.put(key, inherited);
            if (inherited.equals(csClassName)) {
                classNameConflict = true;
            }
        }
    }

    public String methodName(MethodEntry method) {
        return methodName(method.getName(), method.getDesc());
    }

    public String methodName(String name, String descriptor) {
        String assigned = methodNames.get(key(name, descriptor));
        if (assigned == null) {
            throw new IllegalArgumentException("no name assigned for method " + name + descriptor);
        }
        return assigned;
    }

    public String findMethodName(String name, String descriptor) {
        return methodNames.get(key(name, descriptor));
    }

    public boolean declaresKey(String name, String descriptor) {
        return methodNames.containsKey(key(name, descriptor));
    }

    public Integer methodAccessOf(String name, String descriptor) {
        return methodAccess.get(key(name, descriptor));
    }

    public String fieldName(FieldEntry field) {
        return fieldName(field.getName(), field.getDesc());
    }

    public String fieldName(String name, String descriptor) {
        String assigned = fieldNames.get(key(name, descriptor));
        if (assigned == null) {
            throw new IllegalArgumentException("no name assigned for field " + name + " " + descriptor);
        }
        return assigned;
    }

    public String findFieldName(String name, String descriptor) {
        return fieldNames.get(key(name, descriptor));
    }

    /**
     * The override-relevant name assignments this type exports to subtypes: everything it
     * inherited plus its own non-private, non-static method names.
     */
    public Map<String, String> overridableAssignments() {
        Map<String, String> merged = new LinkedHashMap<>(inheritedAssignments);
        for (Map.Entry<String, String> entry : methodNames.entrySet()) {
            Integer access = methodAccess.get(entry.getKey());
            if (access != null && !Modifiers.isPrivate(access) && !Modifiers.isStatic(access)) {
                merged.put(entry.getKey(), entry.getValue());
            }
        }
        return merged;
    }

    /**
     * Every C# member name visible on this type, for reservation in subtypes.
     */
    public Set<String> allMemberNames() {
        return Set.copyOf(taken);
    }

    public boolean hasClassNameConflict() {
        return classNameConflict;
    }

    public static boolean isObjectOverride(String name, String descriptor) {
        return OBJECT_OVERRIDES.containsKey(key(name, descriptor));
    }

    public static String initMethodName(String descriptor) {
        return "__init" + descriptorSuffix(descriptor);
    }

    public static String descriptorSuffix(String descriptor) {
        StringBuilder sb = new StringBuilder(descriptor.length());
        for (int i = 0; i < descriptor.length(); i++) {
            char c = descriptor.charAt(i);
            if (c == '/' || c == '(' || c == ')' || c == ';' || c == '[') {
                sb.append('_');
            } else if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
                sb.append(c);
            } else {
                sb.append("_u").append(String.format("%04X", (int) c)).append('_');
            }
        }
        return sb.toString();
    }

    private void assignFieldNames(ClassFile classFile, Set<String> taken) {
        for (FieldEntry field : classFile.getFields()) {
            String candidate = unique(CsNamer.identifier(field.getName()), taken);
            taken.add(candidate);
            localReserved.add(candidate);
            fieldNames.put(key(field.getName(), field.getDesc()), candidate);
        }
    }

    private void assignMethodNames(ClassFile classFile, TypeMapper typeMapper, Set<String> taken) {
        Map<String, String> baseByJavaName = new LinkedHashMap<>();
        for (MethodEntry method : classFile.getMethods()) {
            String assigned = methodNames.get(key(method.getName(), method.getDesc()));
            if (assigned != null) {
                baseByJavaName.putIfAbsent(method.getName(), assigned);
            }
        }
        for (MethodEntry method : classFile.getMethods()) {
            String name = method.getName();
            if (name.equals("<init>") || name.equals("<clinit>") || methodNames.containsKey(key(name, method.getDesc()))) {
                continue;
            }
            if (!baseByJavaName.containsKey(name)) {
                String candidate = unique(CsNamer.identifier(name), localReserved);
                localReserved.add(candidate);
                taken.add(candidate);
                baseByJavaName.put(name, candidate);
            }
        }
        Map<String, List<MethodEntry>> byBaseAndParams = new LinkedHashMap<>();
        for (MethodEntry method : classFile.getMethods()) {
            String name = method.getName();
            if (name.equals("<init>") || name.equals("<clinit>")) {
                continue;
            }
            String base = baseByJavaName.get(name);
            if (base == null) {
                continue;
            }
            String group = base + "|" + paramSignature(method.getDesc(), typeMapper);
            byBaseAndParams.computeIfAbsent(group, g -> new ArrayList<>()).add(method);
        }
        for (List<MethodEntry> group : byBaseAndParams.values()) {
            for (MethodEntry method : group) {
                if (methodNames.containsKey(key(method.getName(), method.getDesc()))) {
                    continue;
                }
                String base = baseByJavaName.get(method.getName());
                String name = group.size() == 1
                        ? base
                        : base + "__r" + descriptorSuffix(returnDescriptor(method.getDesc()));
                methodNames.put(key(method.getName(), method.getDesc()), name);
            }
        }
    }

    private static String unique(String base, Set<String> taken) {
        String candidate = base;
        int n = 2;
        while (taken.contains(candidate)) {
            candidate = base + "__" + n++;
        }
        return candidate;
    }

    private static String paramSignature(String methodDescriptor, TypeMapper typeMapper) {
        StringBuilder sb = new StringBuilder();
        for (CsType param : typeMapper.paramTypes(methodDescriptor)) {
            sb.append(param.csText()).append(',');
        }
        return sb.toString();
    }

    private static String returnDescriptor(String methodDescriptor) {
        return methodDescriptor.substring(methodDescriptor.indexOf(')') + 1);
    }

    private static String key(String name, String descriptor) {
        return name + descriptor;
    }
}
